---
openapi: 3.0.1
info:
  title: Сервис - barcode в картинку
  description: |-
    Содержит функции для преобразования числового значения barcode в изображения. при этом, \
    существует два варианта функций:
    1. Находится в пространстве имён Api и возвращает результат в одном из полей ответа
    2. Находится в пространстве имён Cdn и возвращает результат как скачиваемый файл. В этом варианте изображения бар \
    кодов можно непосредственно включать в html документ в виде тега <img>, где в качестве src указывается ссылка на \
    entry_point в этом сервисе
  version: v1
paths:
  "/api/barcode_to_image/{barcode}":
    get:
      summary: Получить изображение по бар коду
      tags:
      - Api
      parameters:
      - name: barcode
        in: path
        description: Штрих код для отображения
        required: true
        schema:
          type: string
      - name: format
        in: query
        required: false
        description: 'В каком формате отдать изображение. Доступные варианты: svg,
          png. По умолчанию - svg'
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                to_svg:
                  value:
                    message: Ok
                    barcode: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="119px" height="120px" viewBox="0 0 119 120" version="1.1" preserveAspectRatio="none" >
                      <title>1234567890</title>
                      <g id="canvas" >
                      <rect x="0" y="0" width="119px" height="120px" fill="#fff" />
                      <g id="barcode" fill="#000">
                      <rect x="10" y="10" width="1px" height="100px" />
                      <rect x="12" y="10" width="1px" height="100px" />
                      <rect x="14" y="10" width="3px" height="100px" />
                      <rect x="18" y="10" width="1px" height="100px" />
                      <rect x="22" y="10" width="1px" height="100px" />
                      <rect x="24" y="10" width="1px" height="100px" />
                      <rect x="26" y="10" width="3px" height="100px" />
                      <rect x="32" y="10" width="3px" height="100px" />
                      <rect x="36" y="10" width="3px" height="100px" />
                      <rect x="40" y="10" width="1px" height="100px" />
                      <rect x="44" y="10" width="1px" height="100px" />
                      <rect x="46" y="10" width="1px" height="100px" />
                      <rect x="50" y="10" width="3px" height="100px" />
                      <rect x="54" y="10" width="1px" height="100px" />
                      <rect x="58" y="10" width="3px" height="100px" />
                      <rect x="64" y="10" width="1px" height="100px" />
                      <rect x="66" y="10" width="1px" height="100px" />
                      <rect x="68" y="10" width="1px" height="100px" />
                      <rect x="72" y="10" width="1px" height="100px" />
                      <rect x="74" y="10" width="1px" height="100px" />
                      <rect x="76" y="10" width="3px" height="100px" />
                      <rect x="82" y="10" width="3px" height="100px" />
                      <rect x="86" y="10" width="1px" height="100px" />
                      <rect x="88" y="10" width="3px" height="100px" />
                      <rect x="92" y="10" width="1px" height="100px" />
                      <rect x="96" y="10" width="3px" height="100px" />
                      <rect x="102" y="10" width="1px" height="100px" />
                      <rect x="104" y="10" width="3px" height="100px" />
                      <rect x="108" y="10" width="1px" height="100px" />

                      </g></g>
                      </svg>
                    format: svg
        '400':
          description: arguments error
          content:
            application/json:
              examples:
                wrong format value:
                  value:
                    message: 'Wrong value of format: xml'
  "/api/html_to_pdf":
    post:
      summary: Получить pdf из html
      tags:
      - Api
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: bad arguments
          content:
            application/json:
              examples:
                simple_response:
                  value:
                    message: '["Html text can''t be blank"]'
                  summary: Не заполнен параметр
                  description: Параметр html_text должен быть заполнен
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/options"
            examples:
              request_example_1:
                summary: Простой пример
                value:
                  options:
                    html_text: "<!DOCTYPE html><html><head></head><body>Hellow world!</body></html>"
                    header_html: "<!DOCTYPE html><html><head></head><body>This is
                      header</body></html>"
                    footer_html: "<!DOCTYPE html><html><head></head><body>This is
                      footer</body></html>"
                    orientation: Landscape
                    page_size: Letter
                    margin:
                      top: 50
              request_example_2:
                summary: Переменные в header и footer
                value:
                  options:
                    html_text: "<!DOCTYPE html><html><head></head><body>Hellow world!</body></html>"
                    header_html: <!DOCTYPE html><html><head></head><body>Date <span
                      class="date"></span> Time <span class="time"></span> Sitepage
                      <span class="sitepage"></span></body></html>
                    footer_html: <!DOCTYPE html><html><head></head><body>Page <span
                      class="page"></span> of <span class="topage"></span> Webpage
                      <span class="webpage"></span></body></html>
  "/cdn/barcodes/{barcode}":
    parameters:
    - name: barcode
      in: path
      description: barcode
      required: true
      schema:
        type: string
    get:
      summary: Получить Png файл с картинкой штрих кода
      tags:
      - Cdn
      parameters:
      - name: barcode
        in: path
        description: Штрих код для отображения
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/cdn/html_to_pdf":
    post:
      summary: Получить pdf из html
      tags:
      - Cdn
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/options"
            examples:
              request_example_1:
                summary: Простой пример
                value:
                  options:
                    html_text: "<!DOCTYPE html><html><head></head><body>Hellow world!</body></html>"
                    header_html: "<!DOCTYPE html><html><head></head><body>This is
                      header</body></html>"
                    footer_html: "<!DOCTYPE html><html><head></head><body>This is
                      footer</body></html>"
                    orientation: Landscape
                    page_size: Letter
                    margin:
                      top: 50
              request_example_2:
                summary: Переменные в header и footer
                value:
                  options:
                    html_text: "<!DOCTYPE html><html><head></head><body>Hellow world!</body></html>"
                    header_html: <!DOCTYPE html><html><head></head><body>Date <span
                      class="date"></span> Time <span class="time"></span> Sitepage
                      <span class="sitepage"></span></body></html>
                    footer_html: <!DOCTYPE html><html><head></head><body>Page <span
                      class="page"></span> of <span class="topage"></span> Webpage
                      <span class="webpage"></span></body></html>
components:
  schemas:
    error_response:
      type: object
      properties:
        message:
          type: string
    options:
      type: object
      properties:
        options:
          "$ref": "#/components/schemas/pdf_from_string_params"
    pdf_from_string_params:
      type: object
      properties:
        html_text:
          type: string
          required: true
          description: Основной HTML код который будет преобразован в pdf документ
        header_html:
          type: string
          allowEmptyValue: true
          description: HTML для заголовков страниц
        footer_html:
          type: string
          allowEmptyValue: true
          description: HTML для подвалов(footer) страниц
        orientation:
          type: string
          allowEmptyValue: true
          description: Ориентация страницы
          default: Portrate
          enum:
          - Potrate
          - Landscape
        page_height:
          type: integer
          allowEmptyValue: true
          description: Высота страницы в мм
        page_width:
          type: integer
          allowEmptyValue: true
          description: Ширина страницы в мм
        page_size:
          type: string
          allowEmptyValue: true
          default: A4
          description: Размер страницы из стандартных
          enum:
          - A4
          - Letter
        margin:
          "$ref": "#/components/schemas/margins"
          allowEmptyValue: true
          description: Отступ от краёв листа
    margins:
      type: object
      properties:
        top:
          type: integer
          allowEmptyValue: true
        bottom:
          type: integer
          allowEmptyValue: true
        right:
          type: integer
          allowEmptyValue: true
        left:
          type: integer
          allowEmptyValue: true
